### PR TITLE
Corrupted shapefile

### PR DESCRIPTION
**Pull request by rogup**
**What? Why?**
Closes https://github.com/DigitalCommons/land-explorer-front-end/issues/105

The Shapefile download was not creating a valid file download. This was due to the backend library geojson2shp throwing a "ENOENT: no such file or directory" error when trying to write a shapefile ZIP to a specified file path. I couldn't find any bug reported about this, but found that it worked when specifying a file stream instead of a path, which is what we now do.

**What should we test?**
Create some markers, lines and polygons and save the map.
Click Share -> Export -> Shapefile
Test importing the Shapefile ZIP on an external tool e.g. https://mapshaper.org/ and check that this works ok, with all shapes showing as expected
Repeat for the same map and check that the second ZIP works too

### CODE REVIEW

**Comment by lin-d-hop** [comment]
This is looking great in terms of the download working.

However I get some weird results in my shapefile.

My Map had 4 data points in:
Screenshot from 2022-11-22 13-15-26


However my shapefile is rendering LOADS of data points:
Screenshot from 2022-11-22 13-15-39


Let me know if you want me to share the map (saved as Map777) or shapefile zip with you.

**Comment by rogup** [comment]
I'm on library WiFi at the moment and I'm not able to ssh into the staging server, so can't check the database. I think the extra points might be from a data layer, which would happen if the map was saved with the data layer active, and then you disabled the layer and exported without saving.

If this is the case, maybe we should get the FE to save the map before asking the BE to create a shapefile.

**Comment by lin-d-hop** [comment]
@rogup those data points don't correlate with any data set on staging, so I don't think your theory holds.

**Comment by lin-d-hop** [comment]
Just went to retest and the shapefile didn't download at all. Here is a video:

https://user-images.githubusercontent.com/8669848/205060123-be193a63-3aa7-4268-bdba-7a64e3c4f9f9.mp4

It happened both on the saving of a new map and the second time I saved the map (ie I experienced the issue, then put on record and was able to directly recreate)

**Pull request merged**
